"""Stable compatibility import for the modular :mod:`src.loss` package."""

from src.loss import (
    KimiLossBundle,
    KimiLossConfig,
    KimiPolicyOptimizationLoss,
    KimiPretrainingLoss,
    KimiPretrainingLossOutput,
    KimiRewardComposer,
    KimiTrainingObjective,
    KimiTrainingPhase,
    LossOutput,
    MOPDLossOutput,
    MTPLossOutput,
    MultiTeacherOnPolicyDistillationLoss,
    MultiTokenPredictionLoss,
    NextTokenCrossEntropyLoss,
    PolicyOptimizationLossOutput,
    RewardWeights,
    SFTComponent,
    SFTLossOutput,
    SFTTrajectoryCrossEntropyLoss,
    TokenCrossEntropyOutput,
    TrajectoryRewards,
    apply_reasoning_budget_override,
    apply_verbosity_binary_rule,
    gather_token_logprobs,
)

__all__ = [
    "KimiLossBundle",
    "KimiLossConfig",
    "KimiPolicyOptimizationLoss",
    "KimiPretrainingLoss",
    "KimiPretrainingLossOutput",
    "KimiRewardComposer",
    "KimiTrainingObjective",
    "KimiTrainingPhase",
    "LossOutput",
    "MOPDLossOutput",
    "MTPLossOutput",
    "MultiTeacherOnPolicyDistillationLoss",
    "MultiTokenPredictionLoss",
    "NextTokenCrossEntropyLoss",
    "PolicyOptimizationLossOutput",
    "RewardWeights",
    "SFTComponent",
    "SFTLossOutput",
    "SFTTrajectoryCrossEntropyLoss",
    "TokenCrossEntropyOutput",
    "TrajectoryRewards",
    "apply_reasoning_budget_override",
    "apply_verbosity_binary_rule",
    "gather_token_logprobs",
]
